#define RANDOM_WALLET_STYLE "random_wallet_style"

#define PREF_NOWALLET "No Wallet"
#define PREF_WALLET "Standart Wallet"
#define PREF_BLACKWALLET "Black Wallet"
#define PREF_WHITEWALLET "White Wallet"
#define PREF_TMIWALLET "TMI Wallet"
#define PREF_SYNDIWALLET "Syndicate Wallet"
#define PREF_NTWALLET "NT Wallet"
#define PREF_SFWALLET "SF Wallet"
#define PREF_IQWALLET "InteQ Wallet"
#define PREF_ELYSIUMWALLET "Elysium Wallet"
#define PREF_SEPARWALLET "Separatist Wallet"
#define PREF_PIRATEWALLET "Pirate Wallet"

GLOBAL_LIST_INIT(walletlist, list(
	PREF_NOWALLET,
	PREF_WALLET,
	PREF_BLACKWALLET,
	PREF_WHITEWALLET,
	PREF_TMIWALLET,
	PREF_SYNDIWALLET,
	PREF_NTWALLET,
	PREF_SFWALLET,
	PREF_IQWALLET,
	PREF_ELYSIUMWALLET,
	PREF_SEPARWALLET,
	PREF_PIRATEWALLET
	))
