/obj/effect/spawner/random/outpost_loot
	name = "outpost loot spawner"
	icon_state = "cash"
	spawn_loot_count = 1
	loot = list(
		/obj/item/spacecash/bundle/c1 = 10,
		/obj/item/spacecash/bundle/c10 = 5,
		/obj/item/spacecash/bundle/c20 = 3,
		/obj/item/spacecash/bundle/c50 = 2,
		/obj/item/spacecash/bundle/c100 = 1,
		/obj/item/clothing/head/kitty = 1,
		/obj/effect/spawner/costume/mafia = 1,
		/obj/effect/spawner/costume/mafia/white = 1,
		/obj/effect/spawner/costume/mafia/checkered = 1,
		/obj/effect/spawner/costume/mafia/beige = 1,
		/obj/item/flashlight/lamp = 1,
		/obj/item/flashlight/lamp/green = 1,
		/obj/item/flashlight/lantern = 1,
		/obj/item/passport = 1,
		/obj/item/passport/temporary = 1,
		/obj/item/passport/temporary/diplomat = 1,
		/obj/item/passport/solgov = 1,
		/obj/item/passport/cobrastan = 1,
		/obj/item/storage/fancy/ringbox/diamond = 1,
		/obj/item/storage/fancy/ringbox/silver = 1,
		/obj/item/clothing/under/dress/flower = 1,
		/obj/item/clothing/under/dress/wedding = 1,
		/obj/item/clothing/under/dress/wedding/orange = 1,
		/obj/item/clothing/under/dress/wedding/purple = 1,
		/obj/item/clothing/under/dress/wedding/blue = 1,
		/obj/item/clothing/under/dress/wedding/red = 1,
		/obj/item/clothing/head/centhat = 1,
		/obj/item/clothing/head/centcom_cap = 1,
		/obj/item/clothing/head/that = 1,
		/obj/item/clothing/head/nursehat = 1,
		/obj/item/clothing/head/snowman = 1,
		/obj/item/clothing/head/pirate = 1,
		/obj/item/clothing/head/pirate/captain = 1,
		/obj/item/clothing/head/bandana = 1,
		/obj/item/clothing/head/bearpelt = 1,
		/obj/item/clothing/head/fedora = 1,
		/obj/item/clothing/head/fedora/white = 1,
		/obj/item/clothing/head/fedora/beige = 1,
		/obj/item/clothing/head/flatcap = 1,
		/obj/item/clothing/head/hunter = 1,
		/obj/item/clothing/head/cone = 1,
		/obj/item/clothing/head/santa = 1,
		/obj/item/clothing/head/rice_hat = 1,
		/obj/item/clothing/head/papersack = 1,
		/obj/item/clothing/head/papersack/smiley = 1,
		/obj/item/clothing/head/crown = 1,
		/obj/item/clothing/head/frenchberet = 1,
		/obj/item/clothing/head/intern = 1,
		/obj/item/clothing/head/maidheadband = 1,
		/obj/item/clothing/head/cowboy = 1,
		/obj/item/clothing/head/franks_hat = 1,
		/obj/item/clothing/head/sunhat = 1,
		/obj/item/clothing/suit/bluetag = 1,
		/obj/item/clothing/suit/redtag = 1,
		/obj/item/clothing/suit/pirate = 1,
		/obj/item/clothing/suit/pirate/captain = 1,
		/obj/item/clothing/suit/judgerobe = 1,
		/obj/item/clothing/suit/apron/purple_bartender = 1,
		/obj/item/clothing/suit/toggle/owlwings = 1,
		/obj/item/clothing/suit/toggle/owlwings/griffinwings = 1,
		/obj/item/clothing/suit/cardborg = 1,
		/obj/item/clothing/suit/snowman = 1,
		/obj/item/clothing/suit/hooded/carp_costume = 1,
		/obj/item/clothing/suit/hooded/bloated_human = 1,
		/obj/item/clothing/suit/cybersun = 1,
		/obj/item/clothing/suit/straight_jacket = 1,
		/obj/item/clothing/suit/ianshirt = 1,
		/obj/item/clothing/suit/nerdshirt = 1,
		/obj/item/clothing/suit/jacket = 1,
		/obj/item/clothing/suit/jacket/leather = 1,
		/obj/item/clothing/suit/jacket/leather/duster = 1,
		/obj/item/clothing/suit/jacket/leather/duster/command = 1,
		/obj/item/clothing/suit/jacket/miljacket = 1,
		/obj/item/clothing/suit/jacket/letterman = 1,
		/obj/item/clothing/suit/jacket/letterman_red = 1,
		/obj/item/clothing/suit/jacket/letterman_syndie = 1,
		/obj/item/clothing/suit/jacket/letterman_warra = 1,
		/obj/item/clothing/suit/gothcoat = 1,
		/obj/item/clothing/suit/caution = 1,
		/obj/item/clothing/suit/hooded/ablative = 1,	// Под вопросом
		/obj/item/clothing/suit/ghost_sheet = 1,
		/obj/item/clothing/suit/toggle/suspenders/blue = 1,
		/obj/item/clothing/suit/toggle/suspenders/gray = 1,
		/obj/item/clothing/suit/hawaiian = 1,
		/obj/item/clothing/suit/hawaiian/pink = 1,
		/obj/item/clothing/suit/hawaiian/red = 1
	)

/obj/effect/spawner/random/outpost_loot/big
	name = "outpost big loot spawner"
	spawn_loot_count = 3

/obj/effect/spawner/random/celadon_drink
	name = "random drink spawner"
	desc = "Spawns a random drink with reagent."
	spawn_loot_count = 1
	loot = list(/obj/item/reagent_containers/food/drinks/drinkingglass = 1)

	//взято с code/modules/reagents/chemistry/reagents/drink_reagents.dm
	var/list/possible_reagents = list(
		/datum/reagent/consumable/orangejuice,
		/datum/reagent/consumable/tomatojuice,
		/datum/reagent/consumable/limejuice,
		/datum/reagent/consumable/carrotjuice,
		/datum/reagent/consumable/berryjuice,
		/datum/reagent/consumable/applejuice,
		/datum/reagent/consumable/poisonberryjuice,
		/datum/reagent/consumable/dote_juice,
		/datum/reagent/consumable/dotu_juice,
		/datum/reagent/consumable/refa_li,
		/datum/reagent/consumable/watermelonjuice,
		/datum/reagent/consumable/lemonjuice,
		/datum/reagent/consumable/banana,
		/datum/reagent/consumable/potato_juice,
		/datum/reagent/consumable/grapejuice,
		/datum/reagent/consumable/milk,
		/datum/reagent/consumable/tiris_milk,
		/datum/reagent/consumable/soymilk,
		/datum/reagent/consumable/coffee,
		/datum/reagent/consumable/tea,
		/datum/reagent/consumable/lemonade,
		/datum/reagent/consumable/brazilian_lemonade,
		/datum/reagent/consumable/tea/arnold_palmer,
		/datum/reagent/consumable/icecoffee,
		/datum/reagent/consumable/hot_ice_coffee,
		/datum/reagent/consumable/icetea,
		/datum/reagent/consumable/comet_trail,
		/datum/reagent/consumable/space_up,
		/datum/reagent/consumable/molten,
		/datum/reagent/consumable/molten/sand,
		/datum/reagent/consumable/lemon_lime,
		/datum/reagent/consumable/pacfuel,
		/datum/reagent/consumable/shoal_punch,
		/datum/reagent/consumable/tonic,
		/datum/reagent/consumable/doctor_delight,
		/datum/reagent/consumable/chocolatepudding,
		/datum/reagent/consumable/vanillapudding,
		/datum/reagent/consumable/cherryshake,
		/datum/reagent/consumable/bluecherryshake,
		/datum/reagent/consumable/pumpkin_latte,
		/datum/reagent/consumable/tadrixxfloat,
		/datum/reagent/consumable/pumpkinjuice,
		/datum/reagent/consumable/blumpkinjuice,
		/datum/reagent/consumable/triple_citrus,
		/datum/reagent/consumable/grape_soda,
		/datum/reagent/consumable/milk/chocolate_milk,
		/datum/reagent/consumable/lunapunch,
		/datum/reagent/consumable/menthol,
		/datum/reagent/consumable/grenadine,
		/datum/reagent/consumable/parsnipjuice,
		/datum/reagent/consumable/pineapplejuice,
		/datum/reagent/consumable/cream_soda,
		/datum/reagent/consumable/sol_dry,
		/datum/reagent/consumable/red_queen,
		/datum/reagent/consumable/bungojuice,
		/datum/reagent/consumable/prunomix,
		/datum/reagent/consumable/aloejuice
	)

	var/glass_type = /obj/item/reagent_containers/food/drinks/drinkingglass
	var/reagent_amount = 50

/obj/effect/spawner/random/celadon_drink/make_item(spawn_loc, type_path_to_make)
	var/obj/item/reagent_containers/glass = new glass_type(spawn_loc)
	var/reagent_type = pick(possible_reagents)
	glass.reagents.add_reagent(reagent_type, reagent_amount)
	return glass
