/obj/structure/closet/secure_closet/medical3/PopulateContents()
	. = ..()
	new /obj/item/health_sensor_monitor(src)
	new /obj/item/implanter(src)
	new /obj/item/organ/cyberimp/chest/vital_sensor(src)
	new /obj/item/organ/cyberimp/chest/vital_sensor(src)
